# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Projects',  url: 'projects'}
- {name: 'Skills', url: 'skills'}
- {name: 'Work History',       url: 'workhistory'}
- {name: 'Education',      url: 'education'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link:    'https://www.linkedin.com/in/ross-lancaster/'}
- {icon: 'envelope', link:   'mailto:rosslancaster3@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
